/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 JNL_04.glb --transform
Files: JNL_04.glb [189.66KB] > /Users/whp/Documents/HTML/WHP WEBSITE ROOT/ASSETS/JNL/JNL Blender/Exports/JNL_04-transformed.glb [79.14KB] (58%)
*/

import { useGLTF } from "@react-three/drei";
import InvisibleWalls from "./InvisibleWalls";
import * as THREE from "three";

export default function JNL(props) {
  const textureLoader = new THREE.TextureLoader();
  const JNLTex = textureLoader.load("/textures/JNL_Bake.jpg");
  JNLTex.flipY = false;
  const { nodes, materials } = useGLTF("/models/JNL.glb");
  return (
    <group {...props} dispose={null}>
      <InvisibleWalls />
      <mesh geometry={nodes.JNL_06.geometry} position={[0, -1, 0]}>
        <meshBasicMaterial map={JNLTex} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/JNL_04-transformed.glb");
