/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Alien.gltf --transform
Files: Alien.gltf [22.75MB] > /Users/whp/Downloads/Alien-transformed.glb [213.1KB] (99%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useEffect } from "react";

export default function Alien(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/Alien-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.ArmatureAction.play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Root} />
        </group>
        <skinnedMesh
          name="Alien_retopo_03"
          geometry={nodes.Alien_retopo_03.geometry}
          material={materials["Default OBJ"]}
          skeleton={nodes.Alien_retopo_03.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Alien-transformed.glb");
