/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/whp/Downloads/whp-portfolio-2021/public/alien-baby.gltf --transform 
Files: /Users/whp/Downloads/whp-portfolio-2021/public/alien-baby.gltf [235.69KB] > /Users/whp/Documents/HTML/WHP_WEBSITE_2025_ROOT/whp-website-2025/public/models/alien-baby-transformed.glb [20.57KB] (91%)
*/

import { useGLTF } from "@react-three/drei";

export default function AlienBaby(props) {
  const { nodes, materials } = useGLTF("/models/alien-baby-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Curve009.geometry} material={materials.Red} />
        <mesh geometry={nodes.Curve009_1.geometry} material={materials.Green} />
      </group>
    </group>
  );
}

useGLTF.preload("/models/alien-baby-transformed.glb");
