/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Apartment_Maquette.glb --transform
Files: Apartment_Maquette.glb [12.2MB] > /Users/whp/Documents/HTML/WHP WEBSITE ROOT/ASSETS/Old Portfolio/Apartment_Maquette-transformed.glb [1.64MB] (87%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Apartment(props) {
  const { nodes, materials } = useGLTF(
    "/models/Apartment_Maquette-transformed.glb",
  );

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube067.geometry} material={materials.Palette} />
      <mesh geometry={nodes.Cube067_1.geometry} material={materials.Carpet} />
      <mesh
        geometry={nodes.Cube067_2.geometry}
        material={materials.CuriosCabinet}
      />
      <mesh geometry={nodes.Cube067_3.geometry} material={materials.Blanket} />
      <mesh geometry={nodes.Cube067_4.geometry} material={materials.Mattress} />
      <mesh geometry={nodes.Cube067_5.geometry} material={materials.PIllow} />
      <mesh
        geometry={nodes.Cube067_6.geometry}
        material={materials.SinkCabinet}
      />
      <mesh geometry={nodes.Cube067_7.geometry} material={materials.Ceiling} />
      <mesh geometry={nodes.Cube067_8.geometry} material={materials.Counter} />
      <mesh geometry={nodes.Cube067_9.geometry} material={materials.Wall} />
      <mesh
        geometry={nodes.Cube067_10.geometry}
        material={materials.BedFrame}
      />
    </group>
  );
}

useGLTF.preload("/Apartment_Maquette-transformed.glb");
