/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/whp/Downloads/dragon.gltf --transform 
Files: /Users/whp/Downloads/dragon.gltf [617.32KB] > /Users/whp/Documents/HTML/WHP_WEBSITE_2025_ROOT/whp-website-2025/public/models/dragon-transformed.glb [601.2KB] (3%)
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/public/models/dragon-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.dragon.geometry}
        material={materials["Default OBJ.001"]}
      />
    </group>
  );
}

useGLTF.preload("/public/models/dragon-transformed.glb");
