/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/whp/Documents/HTML/WHP_WEBSITE_2025_ROOT/ASSETS/durers-solid/durers-solid.glb --transform
Files: /Users/whp/Documents/HTML/WHP_WEBSITE_2025_ROOT/ASSETS/durers-solid/durers-solid.glb [1.86KB] > /Users/whp/Documents/HTML/WHP_WEBSITE_2025_ROOT/whp-website-2025/public/models/durers-solid-transformed.glb [1.1KB] (41%)
*/
import { useGLTF } from "@react-three/drei";

export default function DurersSolid(props) {
  const { nodes } = useGLTF("/public/models/durers-solid-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Duerers_Solid.geometry}>
        <meshPhongMaterial />
      </mesh>
    </group>
  );
}

useGLTF.preload("/durers-solid-transformed.glb");
