/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/whp/Documents/HTML/WHP_WEBSITE_2025_ROOT/ASSETS/plinth/plinth.glb --transform 
Files: /Users/whp/Documents/HTML/WHP_WEBSITE_2025_ROOT/ASSETS/plinth/plinth.glb [3.91KB] > /Users/whp/Documents/HTML/WHP_WEBSITE_2025_ROOT/whp-website-2025/public/models/plinth-transformed.glb [1.4KB] (64%)
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes } = useGLTF("/models/plinth-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plinth.geometry}>
        <meshPhongMaterial />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/plinth-transformed.glb");
